#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

CORE_SCRIPT="/etc/ngrok/core/ngrok"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c "$CORE_SCRIPT start && sleep infinity"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    $CORE_SCRIPT stop
}

reload_service() {
    stop
    sleep 2
    start
}