version: "2"
authtoken: "YOUR_NGROK_AUTH_TOKEN"
log: "/var/log/ngrok/ngrok.log"
region: "ap"

tunnels:
  luci:
    proto: http
    addr: 80
  ttyd:
    proto: http
    addr: 192.168.2.1:7681
  ssh:
    proto: tcp
    addr: 22
